### PR TITLE
Fix an issue with locating Rubocop config

### LINKED ISSUE #2: Issue with .rubocop.yml
When using this plug-in the configuration file `.rubocop.yml` is not properly loaded. By default haml-lint looks for the `.rubocop.yml` in the current and parent directories, but this won't work when the linter creates the temporary file in `/tmp/SublimeLinter3-...`.

Currently haml-lint relies on [HAML_LINT_RUBOCOP_CONF](https://github.com/brigade/haml-lint/blob/master/lib/haml_lint/linter/README.md#rubocop) ENV variable. Is there a way that a value for this variable can be passed to the the plugin without starting sublime like this:
`HAML_LINT_RUBOCOP_CONF=/some_path/.rubocop.yml subl`?

### PR DESCRIPTION
**Pull request by kamen-hursev**
This PR fixes #2 in more or less the same way [SublimeLinter-slim-lint](https://github.com/elstgav/SublimeLinter-slim-lint/blob/master/linter.py) is implemented

### CODE REVIEW

**Comment by kamen-hursev** [comment]
@jeroenj, if I fix this lint error `D211: No blank lines allowed before class docstring`, then I get another (that a blank line is required). Eventually I left this the way it was before. 

Is there something not properly configured with the linter?

**Comment by jeroenj** [comment]
What happens if you add an extra newline above line 16 (`class HamlLint(RubyLinter):`)? In your PR you've removed one of the newlines. Maybe that's causing the linter to warn? [SublimeLinter-contrib-haml-lint](https://github.com/elstgav/SublimeLinter-slim-lint/blob/64e1acba0fc43c96243558702defb35a1903683e/linter.py#L15-L16) also has two newlines in there.

I can't test your changes but from what I can see in the code I'd expect them to work. :)

If adding the newline doesn't work I'll accept this PR as it is. But if I remember correctly SublimeLinter "requires" the linters to have no lint errors. (how meta :smile:)

**Comment by kamen-hursev** [comment]
Even if I add the new line I still get the same error. And the error is not (as far as I understand) about that new line, but about the line between `class HamlLint(RubyLinter):` and the docstring below it.
But if the code is the way it is not I get the error you see in Travis. If I change the code like this:

```
class HamlLint(RubyLinter):
    """Provides an interface to haml-lint."""
```

I get: 

```
projects/SublimeLinter-contrib-haml-lint$ pep257 . --ignore=D202
./linter.py:16 in public class `HamlLint`:
        D203: 1 blank line required before class docstring (found 0)
```

I'll add the new line that is missing, but the issue will still be there. These two D203 and D211 seem in conflict as described [here](https://github.com/PyCQA/pydocstyle/issues/141)

**Comment by jeroenj** [comment]
Funny. I'd say to ignore `D203` too which seems [advised](https://github.com/PyCQA/pydocstyle/pull/91#issuecomment-69332089). Could you add it to the Travis setup so that the build succeeds? I'll merge it afterwards.

Thanks a lot for the investigation! :+1:

**Comment by kamen-hursev** [comment]
OK, ignored `D203`, removed the blank line. The build is supposed to pass now (or at least it does locally :smile:)

**Comment by jeroenj** [comment]
Looks goot. Thanks! :smile:

**Comment by LeEnno** [comment]
Unfortunately this doesn't work for me.

Does this setting have to be a linter setting or a meta setting? In other words, which one is right?

``` javascript
{
    // A
    "linters": {
        "hamllint": {
            "rubocop-config": "/path/to/.rubocop.yml"
        }
    },
    // B
    "rubocop-config": "/path/to/.rubocop.yml"
}
```

I also see the printed path in the log (due to `print(rubocop_config)`), so I guess the transmission to the plugin works. The config path seems to get lost somewhere else. Maybe the environment variable can't be read by haml-lint in certain cases?

Any ideas?

**Comment by kamen-hursev** [comment]
You need to specify the configuration as you example A. However you need to specify just the filename (NOT the full path) and the config yml file needs to be somewhere in the parent directories of the linted file.

If all of the above doesn't help you might need to restart Sublime (unfortunately).

**Comment by LeEnno** [comment]
> However you need to specify just the filename (NOT the full path) and the config yml file needs to be somewhere in the parent directories of the linted file.

I tried that, but unfortunately it didn't (and doesn't) work.

Current situation:
- in linter settings under `user` -> `linters` -> `hamllint` I wrote `"rubocop-config": ".rubocop.yml"`
- rubocop.yml path: `/Users/Enno/Sites/pictrs/master/pictrs/.rubocop.yml`
- rubocop.yml contents:

``` yml
Style/HashSyntax:
  Enabled: false
```
- file path: `/Users/Enno/Sites/pictrs/master/pictrs/app/views/adminbill/river.html.haml`
- file contents:

``` haml
%div{ :id => 'container' }
```
- error in Sublime: `RuboCop: Style/HashSyntax: Use the new Ruby 1.9 hash syntax`

Any other ideas?

**Comment by kamen-hursev** [comment]
Unfortunately no. Even without the config value the linter looks for `.rubocop.yml`. Make sure you have up-to-date versions of rubocop, haml-lint and that running haml-lint from the console works fine. 

If you enable debug mode for SublimeLinter `user`->`debug`. You should see something like:
`SublimeLinter: hamllint: file.html.haml ['/home/khursev/.rbenv/shims/ruby', '-S', 'haml-lint', '--config', '<path_to_haml_lint>/.haml-lint.yml']` this is the command SublimeLinter executes for file.html.haml

I don't have other ideas

**Comment by LeEnno** [comment]
Thanks for help.

This is the output I get:

```
SublimeLinter: hamllint version query: /Users/Enno/.rvm/bin/rvm-auto-ruby -S haml-lint --version 
SublimeLinter: hamllint version: 0.13.0 
SublimeLinter: hamllint: (>= 0.6.0) satisfied by 0.13.0 
SublimeLinter: hamllint activated: ['/Users/Enno/.rvm/bin/rvm-auto-ruby'] 
/Users/Enno/Sites/pictrs/master/pictrs/.rubocop.yml
SublimeLinter: hamllint: river.html.haml ['/Users/Enno/.rvm/bin/rvm-auto-ruby', '-S', 'haml-lint']
```

As you can see I use rvm instead of rbenv, but this shouldn't be the cause of the issue, I think. Also I'm missing the config path for `.haml-lint.yml`. Is this necessary for the `.rubocop.yml` to be recognized?

**Comment by kamen-hursev** [comment]
`hamllint version: 0.13.0` the latest one is `0.16.0` is there a reason not to update?

Also try running this :

```
/Users/Enno/.rvm/bin/rvm-auto-ruby -S haml-lint /Users/Enno/Sites/pictrs/master/pictrs/app/views/adminbill/river.html.haml
```

to identify if the problem is in the linter or the Sublime plugin.

**Comment by LeEnno** [comment]
> is there a reason not to update?

I think 0.13.0 is just the version the gemfile loaded with all of its dependency resolving magic.

Running your command from the terminal works fine and respect the `.rubocop.yml`.

**Comment by kamen-hursev** [comment]
`haml-lint 0.13.0` doesn't seem to care about the ENV variable that in our case is needed to properly locate `.rubocop.yml`. They introduced the e

**Comment by LeEnno** [comment]
Ok, first off let me tell you that I love you very much right now ❤️

It turns out that there's a gem called `haml-lint` which is only maintained until version 0.13.0. The project which cares for further development and is at version 0.16.2 right now, is called `haml_lint` (underscore). This is quite confusing since the executable is still called `haml-lint`.

Once I installed the underscored version, it works totally fine. Thanks for pointing that out and bearing with me.

Nevertheless the documentation of this plugin could prevent others from running into this issue. Time for a p-p-pull request.

**Pull request merged**
